apiVersion: apps/v1
kind: Deployment
metadata:
  name: asgbuggy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asgbuggy
  template:
    metadata:
      labels:
        app: asgbuggy
    spec:
      containers:
      - name: asgbuggy
        image: 490167669940.dkr.ecr.ap-southeast-1.amazonaws.com/my-ecr-repo-op:secops-137
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8080 
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: asgbuggy
    k8s-app: asgbuggy
  name: asgbuggy
spec:
 ports:                      # Forward incoming connections on port 8080 to the target port 8080
   - name: http
     port: 8080
     targetPort: 8080
 type: LoadBalancer
 selector:
   app: asgbuggy
