apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot-app-op
  name: springboot-app-op
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app-op
  template:
    metadata:
      labels:
        app: springboot-app-op
    spec:
      containers:
      - name: springboot-app-op
        image: 490167669940.dkr.ecr.ap-southeast-1.amazonaws.com/my-ecr-repo-op:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
          name: http
          protocol: TCP
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-app-op
    k8s-app: springboot-app-op
  name: springboot-app-op
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8085
  type: LoadBalancer
  selector:
    app: springboot-app-op
