name: Java Spring CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - name: Install dependencies and build
        run: mvn -B package --file pom.xml -Pprod -DskipTests
      - name: Build Docker image
        run: docker build . --tag my-image:${{ github.sha }}
      - name: Push Docker image to Amazon ECR
        run: |
          aws ecr get-login-password | docker login --username AWS --password-stdin ${ECR_REGISTRY}
          docker tag my-image:${{ github.sha }} ${ECR_REGISTRY}/my-image:${{ github.sha }}
          docker push ${ECR_REGISTRY}/my-image:${{ github.sha }}
