name: Java Spring CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      APP_NAME: eks-java
      ECR_REPO: my-eks-repo-op
      AWS_REGION: ap-southeast-1
      APP: eks-java
      ECR_URI: "490167669940.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:${{ env.APP }}-${{ github.run_number }}"
      IMAGE_TAG: "java-${{ github.run_number }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build an image
        run: |
          mvn clean install
          docker build -t my-eks-repo-op .

      - name: Push to ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin 490167669940.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
          docker tag my-eks-repo-op:latest 490167669940.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:latest
          docker push 490167669940.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:latest

      - name: Deploy On AWS EKS
        run: |
          aws eks update-kubeconfig --name sandboxeks1 --region ${{ env.AWS_REGION }}
          kubectl get pods -o wide
