name: Deploy Spring Boot Application to AWS EKS

on:
  push:
    branches:
      - master

env:
  AWS_REGION: ap-southeast-1
  ECR_REGISTRY: my-eks-repo-op
  ECR_REPOSITORY: my-eks-repo-op
  KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        id: build-image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          registry: ${{ steps.login-ecr.outputs.registry }}
          
      - name: Get Kubernetes credentials
        uses: tale/kubectl-action@v1
        with:
          kubeconfig-data: ${{ env.KUBE_CONFIG_DATA }}

     
