name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
        env:
          AWS_REGION: ap-southeast-1
          AWS_DEFAULT_REGION: ap-southeast-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          aws-region: ap-southeast-1
      - name: Build with Maven
        run: mvn clean install
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.ECR_REGISTRY }}/my-ecr-repo-op:latest
          build-args: |
            JAR_FILE=target/websocket-demo-0.0.1-SNAPSHOT.jar
          env:
            ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        env:
          AWS_REGION: ap-southeast-1
          AWS_DEFAULT_REGION: ap-southeast-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      - name: Render Amazon ECS task definition
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: maven-java-ecs
          container-name: maven-java-cnt
          image: ${{ secrets.ECR_REGISTRY }}/my-ecr-repo-op:latest
        env:
          AWS_REGION: ap-southeast-1
          ECR_REPOSITORY: my-ecr-repo-op
          ECS_SERVICE: spring-boot-op
          ECS_CLUSTER: my-ecs-cluster
          ECS_TASK_DEFINITION: maven-java-ecs
          CONTAINER_NAME: maven-java-cnt
          AWS_DEFAULT_REGION: ap-southeast-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
